---

- name: geerlingguy.ntp
  version: 2.3.0

- name: geerlingguy.git
  version: 3.0.0

- name: geerlingguy.apache
  version: 3.1.4

- name: geerlingguy.php
  version: 4.6.1

- name: geerlingguy.apache-php-fpm
  version: 1.1.0