---

- name: Settings default vars for extra roles
  set_fact:
    ntp_timezone: America/Argentina/Buenos_Aires
    ntp_package: chrony
    ntp_daemon: chrony
    php_enable_php_fpm: true
    apache_mods_enabled:
      - ssl.load
      - rewrite.load
      - deflate.load
      - headers.load
      - expires.load
    apache_vhosts_ssl:
      - servername: "{{ nfsen_servername }}"
        documentroot: "{{ nfsen_documentroot }}"
        allow_override: all
        certificate_file: "/etc/ssl/certs/example.crt"
        certificate_key_file: "/etc/ssl/private/example.key"
        certificate_chain_file: "/etc/ssl/certs/certificate_chain.crt"
        extra_parameters: |
              ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ nfsen_documentroot }}"
    php_packages_extra:
      - php-rrd
    php_date_timezone: America/Argentina/Buenos_Aires
    extra_parameters: |
      <Location "/">
        Require valid-user
        AuthType Basic
        AuthName "Please authenticate"
        AuthUserFile /etc/apache2/.htpasswd.nfsen
      </Location>

- name: role ntp
  include_role:
    name: geerlingguy.ntp
  when: nfsen_install_ntp | default(true)

- name: role git
  include_role:
    name: geerlingguy.git
  when: nfsen_install_git | default(true)

- name: create user
  community.general.htpasswd:
    path: /etc/apache2/.htpasswd.nfsen
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    owner: root
    group: www-data
    mode: 0640
  loop: "{{ nfsen_users }}"

- name: role apache
  include_role:
    name: geerlingguy.apache
  when: nfsen_install_apache_php | default(true)

- name: role php
  include_role:
    name: geerlingguy.php
  when: nfsen_install_apache_php | default(true)

- name: Configure php-cli timezone
  ansible.builtin.lineinfile:
    path: /etc/php/7.3/cli/php.ini
    regexp: '^date.timezone'
    line: "date.timezone = America/Argentina/Buenos_Aires"
  when: nfsen_install_apache_php | default(true)

- name: role apache-php
  include_role:
    name: geerlingguy.apache-php-fpm
  when: nfsen_install_apache_php | default(true)
