---

- name: Install dependencies to compile nfdump
  apt:
    pkg:
      - build-essential
      - automake
      - flex
      - bison
      - zlib1g-dev
      - libpcap-dev
      - libbz2-dev
      - rrdtool
      - librrd-dev
    update_cache: true

- name: Clone nfdump
  git:
    repo: "{{ nfdump_gitrepo }}"
    dest: /usr/src/nfdump
    force: true
    update: true
    version: "{{ nfdump_version }}"

- name: Autogen
  command:
    cmd: ./autogen.sh
    chdir: /usr/src/nfdump
  changed_when: false

- name: Configure
  command:
    cmd: ./configure --enable-nsel --enable-sflow --enable-nfprofile --enable-nftrack --enable-readpcap --enable-nfpcapd
    chdir: /usr/src/nfdump
  changed_when: false

- name: Make
  make:
    chdir: /usr/src/nfdump

- name: Make Install
  make:
    target: install
    chdir: /usr/src/nfdump

- name: Add libraries to ld
  copy:
    content: |
      /usr/local/lib
    dest: /etc/ld.so.conf.d/nfdump.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Run ldconfig
  command:
    cmd: ldconfig
  changed_when: false
